### ISSUE TITLE
URGENT - Projects Additions to the MAP - Awardees 2018

### ISSUE THREAD

**Issue by rgarciasantos** [earthblink/nomis-foundation#15]
Dear colleagues,

Please kindly note we have the logos of the organizations from the 2018 Awardees but they are missing in the Awardees Map section. 

1- Would you add the 2018 Awardees in the Map
Would you kindly include the link to the Awardees pages as it has been done with Victoria Orphan?

2-  Would you include the links to their info on the NOMIS website? In Victoria Orphan it is done but it is missing in the other two awardees.

Didier Fassin
Learn more: https://nomisfoundation.ch/awards/didier-fassin-nomis-distinguished-scientist-awardee-2018/

Don Cleveland
Learn more: https://nomisfoundation.ch/awards/don-cleveland-nomis-distinguished-scientist-2018/ 

Once is done I will send the Teaser email to them. Meaning I cannot send it without adding that info first.

Lastly, thank you so much for uploading news posts on Janelle Ayres, it is looking great! 

MAny thanks

**Comment by earthblink** [comment]
The Awardees have been added on the map
