### ISSUE TITLE
URGENT please add Don W Cleveland, Victoria Orphan and Didier Fassin to AWARDEES section 

### ISSUE THREAD

**Issue by rgarciasantos** [earthblink/nomis-foundation#17]
Dear colleagues, 
Following previous request, may I kindly ask to add the 2018 awardees to the section of Awardees profiles. You have all the text, images and links already in NOMISnet in their profiles and under the logo sections.
Many thanks indeed,
RUben

**Comment by earthblink** [comment]
The Awardees have been added
