### ISSUE TITLE
Please post Jannelle Ayres Announcement on NOMISnet under "Announcements"

### ISSUE THREAD

**Issue by rgarciasantos** [earthblink/nomis-foundation#4]
Kalimera colleagues
Please post Jannelle Ayres Announcement on NOMISnet under "Announcements"
In this link you will find the text, images and hyperlinks: https://nomisfoundation.ch/news/janelle-ayres-wins-blavatnik-national-award-for-young-scientists/
Many thanks
RUben

**Comment by earthblink** [comment]
Dear Ruben, 

Tis has already been online since June 14th

https://community.nomisfoundation.ch/announcements/janelle-ayres-is-finalist-for-2018-blavatnik-national-awards-for-young-scientists/

**Comment by earthblink** [comment]
*This

**Comment by rgarciasantos** [comment]
Dear Colleagues,

The post is the previous one (finalist). Please  delete the previous one and proceed with the new post it as indicated.
Please let me know if you have any other questions.
Kindest regards
Ruben

Sent from my iPhone

On 17 Jul 2018, at 23:07, EARTHBLINK <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Ruben,

Tis has already been online since June 14th

https://community.nomisfoundation.ch/announcements/janelle-ayres-is-finalist-for-2018-blavatnik-national-awards-for-young-scientists/

-
