### ISSUE TITLE
NOMISnet Project Descriptions and Logos - update and next steps

### ISSUE THREAD

**Issue by rgarciasantos** [earthblink/nomis-foundation#6]
Dear colleagues,

This week we'll provide you with the project descriptions of the NOMIS app. It would also be great if you could revise the logo formatting to ensure (if feasible) that the logos are more or less in line in terms of dimensions (respecting of course its design). An updating the Logo of Stanford (it is **_**not**_** Stanfotd News Center).

Should you have any questions please do GitHub :)
 
Best wishes,

Ruben

**Comment by earthblink** [comment]
Dear Ruben,

Once we receive the final file with the project description we will add them to the Research grants.

The logotypes have a specified area width to be displayed, therefore depending on the design of each logotype the wider ones like the University of Zurich seem much smaller than the narrow ones like SALK for example.
