### ISSUE TITLE
New members NOMISnet - please include profiles

### ISSUE THREAD

**Issue by rgarciasantos** [earthblink/nomis-foundation#8]
Dear colleagues

We have two new members to include in the App these are:
**Tom Battin**
Picture and Bio can be found here: https://people.epfl.ch/tom.battin?lang=en
Tom Battin, Research Director  Full professor in environmental science and engineering School of Architecture, Civil, and Environmental Engineering (ENAC) Head of the Stream Biofilm and Ecosystem Research Laboratory (SBER) 

**Jesus Crespo Cuaresma**
Picture  can be found here: https://www.wu.ac.at/en/vw1/team/univprofdr-jesus-crespo-cuaresma-head-of-institute/
**Bio**
Jesus Crespo Cuaresma is Director of Economic Analysis at the Wittgenstein Centre and has an oversight function of three WIC Research Groups, Professor of Economics at the Vienna University of Economics and Business (WU), as well as and Research Scholar at the International Institute of Applied Systems Analysis (IIASA). He studied Economics at the University of Sevilla (Spain) and received his PhD from the University of Vienna. He has published numerous articles in renowned scientific journals and acts as a scientific consultant to the World Bank and the Austrian Institute of Economic Research. 

Many thanks indeed,

Ruben

**Comment by earthblink** [comment]
Please find below theri username and passwords

tbattin
tbattin@nomisresearcher!

jcrespo
jcrespo@nomisresearcher!
